### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by schell** [mokus0/hoc#6]
What's the status on this project? Where did you net out? I'm starting a similar project and would like to know what happened, what roadblocks you ran into, etc.

Thanks! :)

**Comment by mokus0** [comment]
It's been quite a while now so I'm not sure the current state of compatibility with the ObjC runtime, but at the time I lost steam, the low level stuff like that was working well but the bindings generation was badly bit-rotted.  A couple others and I were looking into migrating them to using the binding data Apple provided, but those files (at least at that time) didn't contain enough metadata to correctly type the imports in Haskell, so additional glue was needed to pull more metadata from the ObjC runtime.  That's about when my first child was born and I also moved to a new employer, and I unfortunately haven't had the time to work on it since.

**Comment by schell** [comment]
No worries, and thanks for the update. I've talked a bit to @IreneKnapp about the same subject with the result :)
